import { useEffect, useMemo, useState } from "react";
import { api, titleCase } from "../api";
import { useTheme } from "../themeStore";

export default function Dashboard(){
  const [data,setData]=useState(null),[vehicles,setVehicles]=useState([]),[filters,setFilters]=useState({type:"",status:"",region:""}),[error,setError]=useState("");const{isDark,setIsDark}=useTheme();
  useEffect(()=>{Promise.all([api("/dashboard"),api("/vehicles")]).then(([dashboard,fleet])=>{setData(dashboard);setVehicles(fleet)}).catch(e=>setError(e.message))},[]);
  const visible=useMemo(()=>vehicles.filter(v=>(!filters.type||v.type===filters.type)&&(!filters.status||v.status===filters.status)&&(!filters.region||v.region===filters.region)),[vehicles,filters]);
  const statuses=data?.vehicles||{},drivers=data?.drivers||{},trips=data?.trips||{};const cards=[["Vehicles on trip",statuses.ON_TRIP||0],["Available vehicles",statuses.AVAILABLE||0],["In maintenance",statuses.IN_SHOP||0],["Active trips",trips.DISPATCHED||0],["Draft trips",trips.DRAFT||0],["Drivers on duty",drivers.ON_TRIP||0]];const types=[...new Set(vehicles.map(v=>v.type))],regions=[...new Set(vehicles.map(v=>v.region).filter(Boolean))];
  const select=(key,label,options)=><label className="text-xs font-semibold uppercase text-slate-500">{label}<select value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})} className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm normal-case text-slate-800"><option value="">All</option>{options.map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select></label>;
  return <main className={`min-h-screen px-4 py-6 sm:px-8 lg:px-12 ${isDark?"bg-slate-950 text-white":"bg-slate-50 text-slate-800"}`}><div className="mx-auto max-w-7xl"><header className="mb-8 flex items-start justify-between"><div><p className="text-sm font-semibold tracking-wide text-blue-600">FLEET OPERATIONS</p><h1 className="text-3xl font-bold">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Live status from your TransitOps database.</p></div><button onClick={()=>setIsDark(!isDark)} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold text-slate-700">{isDark?"Light":"Dark"}</button></header>{error&&<p className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<section className="mb-7 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-3">{select("type","Vehicle type",types)}{select("status","Status",["AVAILABLE","ON_TRIP","IN_SHOP","RETIRED"])}{select("region","Region",regions)}</section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></article>)}</section><section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-semibold text-slate-800">Fleet overview</h2><p className="mt-1 text-sm text-slate-500">{visible.length} vehicle(s) matching your filters</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Vehicle</th><th className="p-4">Type</th><th className="p-4">Region</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y">{visible.map(v=><tr key={v.id}><td className="p-4 font-semibold">{v.registrationNumber}<span className="ml-2 font-normal text-slate-500">{v.name}</span></td><td className="p-4">{v.type}</td><td className="p-4">{v.region||"—"}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{titleCase(v.status)}</span></td></tr>)}{!visible.length&&<tr><td colSpan="4" className="p-8 text-center text-slate-500">No vehicles match these filters.</td></tr>}</tbody></table></div></section></div></main>;
}
