import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../api";

export default function LoginForm(){
  const navigate=useNavigate(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  const submit=async e=>{e.preventDefault();setSaving(true);setError("");try{await api("/auth/sign-in/email",{method:"POST",body:JSON.stringify({email,password,rememberMe:true})});sessionStorage.setItem("transitopsActiveSession","true");navigate("/dashboard")}catch(err){setError(err.message)}finally{setSaving(false)}};
  const input="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
  return <main className="grid min-h-screen place-items-center bg-slate-50 px-4 py-8"><section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/60 sm:p-8"><Link to="/" className="text-sm font-bold tracking-[0.18em] text-blue-600">TRANSITOPS</Link><h1 className="mt-5 text-3xl font-bold">Welcome back</h1><p className="mt-2 text-sm text-slate-500">Log in to access your live fleet workspace.</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className={input}/></label><label className="block text-sm font-medium">Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className={input}/></label>{error&&<p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<button disabled={saving} className="w-full rounded-lg bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Logging in…":"Log in"}</button></form><p className="mt-6 text-center text-sm text-slate-500">New to TransitOps? <Link to="/signup" className="font-semibold text-blue-600">Create an account</Link></p></section></main>;
}
