import { useEffect, useMemo, useState } from "react";
import { api, currency } from "../api";

export default function ReportsAnalytics(){
  const [rows,setRows]=useState([]),[error,setError]=useState("");
  useEffect(()=>{api("/reports/vehicles").then(setRows).catch(e=>setError(e.message))},[]);
  const summary=useMemo(()=>{const sum=k=>rows.reduce((n,r)=>n+Number(r[k]||0),0);const distance=sum("distanceKm"),fuel=sum("fuelLiters");return{distance,fuel,effectiveness:fuel?distance/fuel:0,cost:sum("operationalCost"),trips:sum("completedTrips")}},[rows]);
  const exportCsv=()=>{const headings=["Vehicle","Completed trips","Distance (km)","Fuel (L)","Fuel efficiency (km/L)","Fuel cost","Maintenance cost","Operational cost"];const content=[headings,...rows.map(r=>[r.registrationNumber,r.completedTrips,r.distanceKm,r.fuelLiters,r.fuelEfficiencyKmPerLiter??"",r.fuelCost,r.maintenanceCost,r.operationalCost])].map(row=>row.join(",")).join("\n");const url=URL.createObjectURL(new Blob([content],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download="vehicle-report.csv";link.click();URL.revokeObjectURL(url)};
  const cards=[["Fleet distance",`${summary.distance.toLocaleString()} km`],["Fuel efficiency",`${summary.effectiveness.toFixed(1)} km/L`],["Operational cost",currency(summary.cost)],["Completed trips",summary.trips]];
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-800 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><header className="mb-7 flex items-start justify-between"><div><p className="text-sm font-semibold tracking-wide text-blue-600">FLEET OPERATIONS</p><h1 className="text-3xl font-bold">Reports & Analytics</h1><p className="mt-1 text-sm text-slate-500">Database-backed vehicle performance and cost metrics.</p></div><button onClick={exportCsv} disabled={!rows.length} className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Export CSV</button></header>{error&&<p className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></article>)}</section><section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-semibold">Vehicle performance report</h2><p className="mt-1 text-sm text-slate-500">Calculated from completed trips, fuel logs, maintenance logs, and expenses.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Vehicle</th><th className="p-4">Completed trips</th><th className="p-4">Distance</th><th className="p-4">Fuel efficiency</th><th className="p-4">Fuel cost</th><th className="p-4">Maintenance</th><th className="p-4">Operational cost</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.vehicleId}><td className="p-4 font-semibold">{r.registrationNumber}</td><td className="p-4">{r.completedTrips}</td><td className="p-4">{Number(r.distanceKm).toLocaleString()} km</td><td className="p-4">{r.fuelEfficiencyKmPerLiter?.toFixed(1) ?? "—"}</td><td className="p-4">{currency(r.fuelCost)}</td><td className="p-4">{currency(r.maintenanceCost)}</td><td className="p-4 font-semibold">{currency(r.operationalCost)}</td></tr>)}{!rows.length&&<tr><td colSpan="7" className="p-8 text-center text-slate-500">No report data found.</td></tr>}</tbody></table></div></section></div></main>;
}
