import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../api";

export default function SignupForm(){
  const navigate=useNavigate(),[form,setForm]=useState({name:"",email:"",password:"",confirmPassword:""}),[error,setError]=useState(""),[saving,setSaving]=useState(false);const set=(key,value)=>setForm({...form,[key]:value});
  const submit=async e=>{e.preventDefault();if(form.password!==form.confirmPassword){setError("Passwords do not match.");return}setSaving(true);setError("");try{await api("/auth/sign-up/email",{method:"POST",body:JSON.stringify({name:form.name,email:form.email,password:form.password})});navigate("/dashboard")}catch(err){setError(err.message)}finally{setSaving(false)}};
  const input="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
  return <main className="grid min-h-screen place-items-center bg-slate-50 px-4 py-8"><section className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/60 sm:p-8"><Link to="/" className="text-sm font-bold tracking-[0.18em] text-blue-600">TRANSITOPS</Link><h1 className="mt-5 text-3xl font-bold">Create your account</h1><p className="mt-2 text-sm text-slate-500">Your account is created through the TransitOps authentication service.</p><form onSubmit={submit} className="mt-7 grid gap-5"><label className="text-sm font-medium">Full name<input required value={form.name} onChange={e=>set("name",e.target.value)} className={input}/></label><label className="text-sm font-medium">Work email<input required type="email" value={form.email} onChange={e=>set("email",e.target.value)} className={input}/></label><label className="text-sm font-medium">Password<input required minLength="6" type="password" value={form.password} onChange={e=>set("password",e.target.value)} className={input}/></label><label className="text-sm font-medium">Confirm password<input required minLength="6" type="password" value={form.confirmPassword} onChange={e=>set("confirmPassword",e.target.value)} className={input}/></label>{error&&<p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<button disabled={saving} className="rounded-lg bg-blue-600 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Creating account…":"Create account"}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link to="/login" className="font-semibold text-blue-600">Log in</Link></p></section></main>;
}
