import { useEffect, useState } from "react";
import { api, titleCase } from "../api";

const empty = { source: "", destination: "", vehicleId: "", driverId: "", cargoWeightKg: "", plannedDistanceKm: "" };
const input = "mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";

export default function TripManagement() {
  const [trips, setTrips] = useState([]), [vehicles, setVehicles] = useState([]), [drivers, setDrivers] = useState([]), [form, setForm] = useState(empty), [error, setError] = useState(""), [notice, setNotice] = useState(""), [saving, setSaving] = useState(false);
  const load = async () => { try { const [t,v,d] = await Promise.all([api("/trips"), api("/vehicles"), api("/drivers")]); setTrips(t); setVehicles(v); setDrivers(d); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const submit = async e => { e.preventDefault(); setSaving(true); setError(""); try { await api("/trips", { method:"POST", body:JSON.stringify(form) }); setForm(empty); setNotice("Draft trip created."); load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const action = async (trip, endpoint) => { setError(""); try { let body; if (endpoint === "complete") { const endOdometer = window.prompt("End odometer (km):", trip.vehicle.odometer); if (endOdometer === null) return; body = JSON.stringify({ endOdometer, actualDistanceKm: window.prompt("Actual distance (km), optional:") || undefined, fuelConsumedLiters: window.prompt("Fuel consumed (L), optional:") || undefined }); } await api(`/trips/${trip.id}/${endpoint}`, { method:"POST", body }); setNotice(`Trip ${endpoint}d successfully.`); load(); } catch (err) { setError(err.message); } };
  const availableVehicles = vehicles.filter(v => v.status === "AVAILABLE"), availableDrivers = drivers.filter(d => d.status === "AVAILABLE");
  return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-800 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><header className="mb-7"><p className="text-sm font-semibold tracking-wide text-blue-600">FLEET OPERATIONS</p><h1 className="text-3xl font-bold">Trip Management</h1><p className="mt-1 text-sm text-slate-500">Plan and run trips using current vehicle and driver availability.</p></header>{error && <p className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{notice && <p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2 xl:grid-cols-3"><h2 className="font-semibold md:col-span-2 xl:col-span-3">Create draft trip</h2>{[["source","Source"],["destination","Destination"]].map(([name,label]) => <label key={name} className="text-sm font-medium">{label} *<input required value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})} className={input}/></label>)}<label className="text-sm font-medium">Available vehicle *<select required value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})} className={input}><option value="">Select vehicle</option>{availableVehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.name}</option>)}</select></label><label className="text-sm font-medium">Available driver *<select required value={form.driverId} onChange={e=>setForm({...form,driverId:e.target.value})} className={input}><option value="">Select driver</option>{availableDrivers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-sm font-medium">Cargo weight (kg) *<input required min="1" type="number" value={form.cargoWeightKg} onChange={e=>setForm({...form,cargoWeightKg:e.target.value})} className={input}/></label><label className="text-sm font-medium">Planned distance (km) *<input required min="1" type="number" value={form.plannedDistanceKm} onChange={e=>setForm({...form,plannedDistanceKm:e.target.value})} className={input}/></label><div className="flex items-end"><button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":"Create trip"}</button></div></form>
    <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-semibold">Trip lifecycle</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Route</th><th className="p-4">Vehicle</th><th className="p-4">Driver</th><th className="p-4">Load / distance</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y">{trips.map(t=><tr key={t.id}><td className="p-4 font-semibold">{t.source} → {t.destination}</td><td className="p-4">{t.vehicle.registrationNumber}</td><td className="p-4">{t.driver.name}</td><td className="p-4">{t.cargoWeightKg} kg / {t.plannedDistanceKm} km</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{titleCase(t.status)}</span></td><td className="p-4 space-x-2">{t.status === "DRAFT" && <><button onClick={()=>action(t,"dispatch")} className="rounded bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white">Dispatch</button><button onClick={()=>action(t,"cancel")} className="text-xs font-semibold text-rose-600">Cancel</button></>}{t.status === "DISPATCHED" && <><button onClick={()=>action(t,"complete")} className="rounded bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">Complete</button><button onClick={()=>action(t,"cancel")} className="text-xs font-semibold text-rose-600">Cancel</button></>}</td></tr>)}{!trips.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">No trips found.</td></tr>}</tbody></table></div></section></div></main>;
}
